added PV collections
sentinel-hub/public-collections pull request #100
Opened 2024-01-08 23:26 UTC by mattballard-planet

added PV pages and subpages for open data collections

2024-01-08 23:28 UTC, mattballard-planet commented
Hi @Dorothyrono, @gmilcinski asked me to connect with you about reviewing this request to add Planetary Variables here, can you review, please?

2024-01-09 09:22 UTC, Dorothyrono commented
on it

2024-01-09 11:53 UTC, Dorothyrono requested changes

2024-01-09 20:12 UTC, mattballard-planet commented on collections/crop-biomass.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](crop-biomass/README.MD);
I was modelling off of this example: https://github.com/sentinel-hub/public-collections/blob/main/collections/vegetation-phenology-and-productivity-parameters-season-2.yaml

which appears to refer to a markdown file. 

I can absolutely change these to readme.html, but just want to double check before I make the change.

also, can the file be named anything? like open-collection.md or open-collection.html?

2024-01-09 20:12 UTC, mattballard-planet commented on collections/crop-biomass.yaml
> +    Notes: Contains the data purchased by individual user. [Explore sample CC-BY-SA open data here](crop-biomass/README.MD).
same comment as before

2024-01-09 20:14 UTC, mattballard-planet commented on collections/land-surface-temperature.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](land-surface-temperature/README.MD);
same response as earlier, will adjust after that discussion

2024-01-10 11:15 UTC, Dorothyrono commented on collections/crop-biomass.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](crop-biomass/README.MD);
Hey Matt,

> I was modelling off of this example: https://github.com/sentinel-hub/public-collections/blob/main/collections/vegetation-phenology-and-productivity-parameters-season-2.yaml
> 
> which appears to refer to a markdown file

It depends on the template

Right, the `AdditionalInfoExternal` refers to a mark down file , as it has a function to compile the markdown file to a html page. quick check [here](https://github.com/sentinel-hub/public-collections/blob/main/gulpfile.js#L291)

The other templates use other functions; in this case `GeographicalCoverage ` template for example takes in simple markdown text . That's why a direct link to the page would work

Same to the `notes` template

2024-01-10 11:52 UTC, Dorothyrono commented on collections/crop-biomass.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](crop-biomass/README.MD);
> also, can the file be named anything? like open-collection.md or open-collection.html?

Yes,  just make it consistent.   

You would have something like this 
```
AdditionalInfoExternal:
    Title: Open Data for Crop Biomass
    Path: crop-biomass/open-collection.md
----
GeographicalCoverage: Global; Open data in [limited areas](open-collection.html); 
Notes: Contains the data purchased by individual user. [Explore sample CC-BY-SA open data here](open-collection.html).
```

Basically, the absolute link is  `https://collections.sentinel-hub.com/crop-biomass/open-collection.html`

2024-01-10 11:59 UTC, Dorothyrono commented on collections/crop-biomass.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](crop-biomass/README.MD);
We will add a tutorial to do a local build of the site,  to make it easier to check the pages before hand

2024-01-10 23:13 UTC, mattballard-planet commented on collections/crop-biomass.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](crop-biomass/README.MD);
ah, got it, I understand now. Let me go make these adjustments

2024-01-10 23:24 UTC, mattballard-planet commented on collections/crop-biomass.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](crop-biomass/README.MD);
okay, I think I've addressed each of these issues. Thanks for offering the tutorial, I wasn't sure how to do a local check. That might be helpful to double check some of the formatting before I push this

2024-01-10 23:24 UTC, mattballard-planet commented on collections/crop-biomass.yaml
> +    Notes: Contains the data purchased by individual user. [Explore sample CC-BY-SA open data here](crop-biomass/README.MD).
fixed

2024-01-11 15:08 UTC, Dorothyrono requested changes

2024-01-11 15:08 UTC, Dorothyrono commented on collections/crop-biomass.yaml
> +GeographicalCoverage: Global; Open data in [limited areas](crop-biomass/open-data.html);
The root url is  `https://collections.sentinel-hub.com/crop-biomass/`. (should have mentioned this already)

Therefore, the link `(crop-biomass/open-data.html)`  is one level too high  

You just need  `(open-data.html)`.  That's it. 

You will see that if you do a local  build , see instructions on how to build the site on local [Link](https://github.com/sentinel-hub/public-collections/blob/main/CONTRIBUTING.md#how-to-build-sentinel-hub-public-collections-website-locally)

2024-01-11 15:08 UTC, Dorothyrono commented on collections/crop-biomass.yaml
> +    Notes: Contains the data purchased by individual user. [Explore sample CC-BY-SA open data here](crop-biomass/open-data.html).
same comment as above and to the rest

2024-01-11 15:16 UTC, mattballard-planet commented on collections/crop-biomass.yaml
> +    Path: crop-biomass/open-data.md
yes, thanks, overlooked that, will do it now

2024-01-11 15:28 UTC, Dorothyrono approved these changes
All good

2024-01-11 15:30 UTC, Dorothyrono commented
Should we merge it ?

or you can merge  it if you have the rights

2024-01-11 15:34 UTC, mattballard-planet commented
@Dorothyrono I don't have the rights to merge it, but yes, I think this is good to go

2024-01-11 17:18 UTC, merged